defaults:
  - /agent/cql/dnn

name: cql_blendrl_human_cew
algorithm: blendrl_cql
actor_mode: hybrid
blender_mode: neural
blend_function: softmax
ecm_dthr: 0.03
fyd_top_k: 150

modules:
  - type: nsfr
    rules: default
  - type: cew
    fyd: true
    ecm_dthr: 0.03
    fyd_top_k: 150

