defaults:
  - /agent/cql/dueling_resnet

name: cql_blendrl_cew_dueling_resnet
algorithm: blendrl_cql
actor_mode: hybrid
blender_mode: neural
blend_function: softmax
architecture: dueling_resnet
ecm_dthr: 0.03
fyd: false

modules:
  - type: cew
    fyd: false
    ecm_dthr: 0.03
  - type: neural
