defaults:
  - /agent/cql/blendrl_human_neural

name: cql_blendrl_human_continuous
algorithm: blendrl_cql
actor_mode: hybrid
blender_mode: neural
blend_function: softmax

modules:
  - type: nsfr
    rules: default
  - type: neural
