defaults:
  - /agent/cql/dnn

name: cql_blendrl_cew_only
algorithm: blendrl_cql
actor_mode: logic
ecm_dthr: 0.03
fyd_top_k: 150

modules:
  - type: cew
    fyd: true
    ecm_dthr: 0.03
    fyd_top_k: 150
