defaults:
  - /agent/cql/dueling_resnet

name: cql_blendrl_human_dueling_resnet
algorithm: blendrl_cql
actor_mode: hybrid
blender_mode: neural
blend_function: softmax
architecture: dueling_resnet

modules:
  - type: nsfr
    rules: ${env.rules}
  - type: neural
