experimentid: cp_test
environment: cartpole
rules: default,variant1,variant2
online_steps: 100000
offline_epochs: 10
eval_episodes: 10
online_methods: ppo,blendrl_ppo
offline_methods: iql,blendrl_iql
offline_datasets: ppo,blendrl_ppo
intervals_count: 5
