experimentid: mc_final_ppo
environment: mountaincar
rules: default,no_left,no_left_blender_right
online_steps: 3000000
offline_epochs: 20
eval_episodes: 100
online_methods: ppo
offline_methods: iql,blendrl_iql
offline_datasets: ppo
intervals_count: 7

# Optimal PPO Parameters (Online Only)
num_envs: 4
num_steps: 1024
lr: 0.0003
ent_coef: 0.08
ppo_epochs: 10
num_minibatches: 64
clip_coef: 0.2

# Offline (Applies to all 3 rulesets)
offline_lr: 0.0003
iql_tau: 0.7
iql_beta: 3.0
batch_size: 256
