experimentid: mc_final_blendrl
environment: mountaincar
rules: default,no_left,no_left_blender_right
online_steps: 3000000
offline_epochs: 20
eval_episodes: 100
online_methods: blendrl_ppo
offline_methods: iql,blendrl_iql
offline_datasets: blendrl_ppo
intervals_count: 7

# OG Parameters
num_envs: 1
num_blend_envs: 1
num_steps: 2048
lr: 0.0003
ent_coef: 0.02
ppo_epochs: 10
num_minibatches: 32
clip_coef: 0.2

# BlendRL Specific
logic_lr: 0.0003
blender_lr: 0.0003
blend_ent_coef: 0.02

# Offline (Applies to all 3 rulesets)
offline_lr: 0.0003
iql_tau: 0.7
iql_beta: 3.0
batch_size: 256
