experimentid: mc_ppo_1
environment: mountaincar
rules: default
online_steps: 5000000
offline_epochs: 1
eval_episodes: 100
online_methods: ppo
offline_methods: ""
offline_datasets: ""
intervals_count: 11

# High Exploration (Inspired by Batch 11)
num_envs: 1
num_steps: 2048
lr: 0.0003
ent_coef: 0.1
ppo_epochs: 10
num_minibatches: 64
clip_coef: 0.2
