experimentid: mc_ppo_4
environment: mountaincar
rules: default
online_steps: 5000000
offline_epochs: 1
eval_episodes: 100
online_methods: ppo
offline_methods: ""
offline_datasets: ""
intervals_count: 11

# High Frequency (Inspired by Batch 14)
num_envs: 1
num_steps: 4096
lr: 0.0003
ent_coef: 0.05
ppo_epochs: 20
num_minibatches: 64
clip_coef: 0.2
