experimentid: seaquest_test
environment: seaquest
rules: default
online_steps: 50000
offline_epochs: 1
eval_episodes: 5
online_methods: ppo,blendrl_ppo
offline_methods: iql,blendrl_iql
offline_datasets: ppo,blendrl_ppo
intervals_count: 2
