# Site profile: NCSU HPC (ncshare) cluster - GPU Nodes (gpu partition)
defaults:
  - ncshare
  - _self_

consolidate: true
gres_format: "gpu:{gpu_type}:{gpus}"   # e.g. gpu:a100:1

# Resources for GPU nodes (partition: gpu)
resources:
  partition: gpu
  gpus: 1
  cores: 16
  memory: "32G"
  no_gres: false

module_loads:
  - "cuda"

extra_env_vars:
  PYTORCH_CUDA_ALLOC_CONF: "expandable_segments:True"
